# Generated by Django 4.2 on 2026-04-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        choices=[
                            ("resnet", "ResNet"),
                            ("vgg", "VGG"),
                            ("mobilenet", "MobileNet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        choices=[("catdog", "猫狗分类"), ("breeds", "狗品种识别")],
                        default="catdog",
                        help_text="任务类型",
                        max_length=20,
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(help_text="测试准确率，如95.5表示95.5%"),
                ),
                ("inference_time", models.FloatField(help_text="平均推理时间（毫秒）")),
                ("model_size", models.FloatField(help_text="模型大小（MB）")),
                (
                    "dataset",
                    models.CharField(help_text="测试数据集名称", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, help_text="备注信息")),
            ],
            options={
                "ordering": ["model_name"],
            },
        ),
        migrations.CreateModel(
            name="ModelConfidenceStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        choices=[
                            ("resnet", "ResNet"),
                            ("vgg", "VGG"),
                            ("mobilenet", "MobileNet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        choices=[("catdog", "猫狗分类"), ("dogbreed", "狗品种识别")],
                        help_text="任务类型",
                        max_length=20,
                    ),
                ),
                ("total_samples", models.IntegerField(help_text="总样本数")),
                ("accuracy", models.FloatField(help_text="准确率，如95.5表示95.5%")),
                (
                    "avg_confidence",
                    models.FloatField(help_text="整体平均置信度，如95.5表示95.5%"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["model_name", "task"],
                "unique_together": {("model_name", "task")},
            },
        ),
        migrations.CreateModel(
            name="ClassConfidenceStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        choices=[
                            ("resnet", "ResNet"),
                            ("vgg", "VGG"),
                            ("mobilenet", "MobileNet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        choices=[("catdog", "猫狗分类"), ("dogbreed", "狗品种识别")],
                        help_text="任务类型",
                        max_length=20,
                    ),
                ),
                ("class_name", models.CharField(help_text="类别名称", max_length=100)),
                ("sample_count", models.IntegerField(help_text="该类别样本数")),
                (
                    "accuracy",
                    models.FloatField(help_text="该类别准确率，如95.5表示95.5%"),
                ),
                (
                    "avg_confidence",
                    models.FloatField(help_text="该类别平均置信度，如95.5表示95.5%"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["model_name", "task", "class_name"],
                "unique_together": {("model_name", "task", "class_name")},
            },
        ),
    ]
