# Generated by Django 4.2 on 2026-04-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visualization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelconfidencestats",
            name="accuracy",
        ),
    ]
