# Generated by Django 4.2 on 2026-04-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visualization", "0002_remove_modelconfidencestats_accuracy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelperformance",
            name="task",
            field=models.CharField(
                choices=[("catdog", "猫狗分类"), ("dogbreed", "狗品种识别")],
                default="catdog",
                help_text="任务类型",
                max_length=20,
            ),
        ),
    ]
