# Generated by Django 4.2 on 2026-04-02 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/%Y/%m/%d/")),
                ("image_name", models.CharField(max_length=255)),
                (
                    "model_used",
                    models.CharField(
                        choices=[
                            ("resnet", "ResNet"),
                            ("vgg", "VGG"),
                            ("mobilenet", "MobileNet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        choices=[("catdog", "猫狗识别"), ("breeds", "狗品种识别")],
                        default="catdog",
                        max_length=10,
                    ),
                ),
                ("prediction", models.CharField(max_length=50)),
                ("display_prediction", models.CharField(default="", max_length=100)),
                ("confidence", models.FloatField()),
                ("inference_time", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
